language: android


android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
  licenses:
    - ".+"

before_install:
  - chmod +x ./gradlew

addons:
  sonarcloud:
    organization: calidad-g7-2020
    token:
      secure: 712cd22e13ad8cefb1ecc835ba3635bd87c77698

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew build
  - ./gradlew sonarqube

branches:
  only:
    - gh-pages
    - master
    - /.*/